const Data = [
  {
    id: "1",
    name: "Question: 1- ",
    text: "Approximate atomic weight of an element is 26.89. If its equivalent weight is 8.9, the exact atomic weight of element would be :",
    a: "(a) 26.89",
    b: "(b) 8.9",
    c: "(c) 17.8",
    d: "(d) 26.7",
    isTrue: "d",
  },
  {
    id: "2",
    name: "Question: 2- ",
    text: "The number of moles present in 6 g of carbon is :",
    a: "(a) 2",
    b: "(b) 0.5",
    c: "(c) 5",
    d: "(d) 1",
    isTrue: "b",
  },
  {
    id: "3",
    name: "Question: 3- ",
    text: "What is the concentration of nitrate ions if equal volumes of 0.1 M AgNO3 and 0.1 M NaCl are mixed together :",
    a: "(a) 0.1 N",
    b: "(b) 0.2 N",
    c: "(c) 0.05 N",
    d: "(d) 0.25 N",
    isTrue: "c",
  },
  {
    id: "4",
    name: "Question: 4- ",
    text: "The -ve charged particles is called :",
    a: "(a) Anion",
    b: "(b) Cation",
    c: "(c) Radical",
    d: "(d) Atom",
    isTrue: "a",
  },
  {
    id: "5",
    name: "Question: 5- ",
    text: "Which is not a unit of pressure :",
    a: "(a) Bar",
    b: "(b) N/m²",
    c: "(c) Kg/m²",
    d: "(d) Torr",
    isTrue: "c",
  },
  {
    id: "6",
    name: "Question: 6- ",
    text: "What is the normality of a 1 M solution of H3PO4 :",
    a: "(a) 0.5 N",
    b: "(b) 1.0 N",
    c: "(c) 2.0 N",
    d: "(d) 3.0 N",
    isTrue: "d",
  },
  {
    id: "7",
    name: "Question: 7- ",
    text: "The total number of ions present in 111 g of CaCl2 is :",
    a: "(a) One Mole",
    b: "(b) Two Mole",
    c: "(c) Three Mole",
    d: "(d) Four Mole",
    isTrue: "c",
  },
  {
    id: "8",
    name: "Question: 8- ",
    text: "Which of the following cannot give iodometric titrations :",
    a: "(a) Fe3+",
    b: "(b) Cu2+",
    c: "(c) Pb2+",
    d: "(d) Ag",
    isTrue: "c",
  },
  {
    id: "9",
    name: "Question: 9- ",
    text: "The significant figures in 3400 are :",
    a: "(a) 2",
    b: "(b) 5",
    c: "(c) 6",
    d: "(d) 7",
    isTrue: "b",
  },
  {
    id: "10",
    name: "Question: 10- ",
    text: "The S.I unit of temperature is :",
    a: "(a) Kelvin",
    b: "(b) Celsius",
    c: "(c) Fahrenheit",
    d: "(d) Centigrade",
    isTrue: "a",
  },
];
export default Data;
